set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN T17 [get_ports rst]
set_property PACKAGE_PIN P19 [get_ports hsync]
set_property PACKAGE_PIN R19 [get_ports vsync]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports {o_blue[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_blue[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_blue[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_blue[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_green[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_green[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_green[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_green[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_red[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_red[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_red[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_red[0]}]

set_property PACKAGE_PIN G19 [get_ports {o_red[0]}]
set_property PACKAGE_PIN H19 [get_ports {o_red[1]}]
set_property PACKAGE_PIN J19 [get_ports {o_red[2]}]
set_property PACKAGE_PIN N19 [get_ports {o_red[3]}]
set_property PACKAGE_PIN J17 [get_ports {o_green[0]}]
set_property PACKAGE_PIN H17 [get_ports {o_green[1]}]
set_property PACKAGE_PIN G17 [get_ports {o_green[2]}]
set_property PACKAGE_PIN D17 [get_ports {o_green[3]}]
set_property PACKAGE_PIN N18 [get_ports {o_blue[0]}]
set_property PACKAGE_PIN L18 [get_ports {o_blue[1]}]
set_property PACKAGE_PIN K18 [get_ports {o_blue[2]}]
set_property PACKAGE_PIN J18 [get_ports {o_blue[3]}]
